spring:
  application:
    name: search-service
  datasource:
    url: ${MYSQL_CONNECTION}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
elasticsearch:
  host: ${ES_HOST}
  port: ${ES_PORT}
  index: ${ES_INDEX}
  search: http://${ES_HOST}:${ES_PORT}/${ES_INDEX}/_search
